### ISSUE TITLE
Custom parameter parsing not working

### ISSUE THREAD

**Issue by Karsten1987** [ros-simulation/gazebo_ros2_control#59]
The custom logic for parsing parameters in the gazebo_plugin does not work as expect. When launching the system with the following parameters:
```
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_controller:
      type: joint_state_controller/JointStateController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
```

I expect to see the parameters set at the controller manager, however `ros2 param list` yields nothing:
```
 ➭ ros2 param list
...
/controller_manager:
  use_sim_time

```
